/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mx.tecnm.delicias.poo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App sut = new App();
        assertEquals("Hello World!", sut.getGreeting(), "The greeting should be Hello World!");
    }
}
